'use strict';

// Your code goes here.
//
// During the "build" step, two versions of your file will be generated by `grunt rigger` and the scripts in the /build folder:
// 1) AMD version
// 2) IIFE version